---
apiVersion: v2
name: kubernetesweekly
description: Get data from kubeweekly and create Weekly CRDs based on community-operator and push to git datastore
version: 2.1.0
appVersion: 2.1.0
type: application
home: https://github.com/zufardhiyaulhaq/kubernetesweekly

maintainers:
- name: Zufar Dhiyaulhaq
  email: zufardhiyaulhaq@gmail.com
  url: https://zufardhiyaulhaq.com

