---
apiVersion: v2
name: kubernetesweekly
description: Get data from kubeweekly and create Weekly CRDs based on community-operator and push to git datastore
version: 2.0.0
appVersion: 1.0.1
type: application
home: https://github.com/zufardhiyaulhaq/kubernetesweekly

maintainers:
- name: Zufar Dhiyaulhaq
  email: zufardhiyaulhaq@gmail.com
  url: https://zufardhiyaulhaq.com

