---
apiVersion: v1
name: kubernetesweekly
type: application
version: 1.0.0
appVersion: 1.0.0
description: kubernetesweekly scrapper
home: https://github.com/zufardhiyaulhaq/kubernetesweekly
keywords:
  - weekly
  - kubernetesweekly
